### ISSUE TITLE
Tracking: Basic SSTable Implementation.

### ISSUE THREAD

**Issue by MrCroxx** [MrCroxx/RunKV#1]
Tracking:

- [x] Block encoding.
- [x] Block decoding.
- [x] Varint encoding.
- [x] SSTable data object encoding.
- [x] SSTable data object decoding.
- [x] SSTable meta object encoding.
- [x] SSTable meta object decoding.
- [x] Binary search on single block.
- [x] Block iterator.
- [x] Contact iterator.
- [x] SSTable iterator (depends on `SstableStore` and `ObjectStore`).
- [x] Merge iterator.
- [x] User key iterator.
- [x] Tombstones.
- [x] User key iterator with tombstones.

**Comment by MrCroxx** [comment]
Close. 🎉

**Comment by MrCroxx** [comment]
Forgot to implement tombstone, reopen, orz.

**Comment by MrCroxx** [comment]
Close via #32 .
